title:              Melvin John Portfolio
url:                "https://melvinj98.github.io"

# Social Profiles
github_username:    melvinj98
linkedin_username:  melvinj98

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
remote_theme:       jekyll-theme-clean-blog
#paginate:           5
#paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
